Strict mismatch error, after fixing three syntax errors, missing : and mispelling of equal, and big; error[E0308]: mismatched types  --> main.rs:23:21 was done dilibertly to inforce strict type matching, it requires the input string be converted to a number of type u32 or other acceptable number type.